name: Python application

on: [push]

jobs:
 e2e-ie:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - run: python -m pip install --upgrade pip
    - run: pip install selenium
    - run: python test.py
      env:
        BROWSER: ie

